FROM node:16-alpine

RUN mkdir client
RUN apk update && apk upgrade && apk add bash

WORKDIR /client

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .

RUN yarn build

CMD ["yarn", "start"]

EXPOSE 3000
