FROM node:16-alpine

RUN mkdir app
RUN apk update && apk upgrade && apk add bash

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .

RUN yarn build

CMD ["yarn", "start"]

EXPOSE 3000
